---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-core-security-svcs
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 0294f96e-7314-48d1-a710-c08a541b2119
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        format_kind: stack
        validation_type: projects
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
