---
apiVersion: v1
offerings:
  - name: core-security-services
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 2f033bd2-009d-4e89-86c2-d5edf8f641a2
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        format_kind: stack
        validation_type: projects
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
